local function countdown(label_url, seconds)
	timer.delay(1, true, function(self, handle, time_elapsed)
		seconds = seconds - 1
		label.set_text(label_url, seconds)
		-- cancel timer when countdown reaches 0
		if seconds == 0 then
			timer.cancel(handle)
		end
	end)
end 

function init(self)
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	collectionfactory.create("#collectionfactory")
	countdown("timer#label", 60)
end
